# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Code Integration to the main branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setting up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.1
        
    - name: Compiling the code
      run: mvn compile
      
    - name: Testing the code
      run: mvn test
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
